### ISSUE TITLE
reformat messages with text attachments

### ISSUE THREAD

**Issue by twouters** [Sorunome/matrix-slack-parser#1]
Current message with text attachments look a bit sturdy, e.g.

`<START MX EXAMPLE>`
Random message text [matrix.org](https://matrix.org)

---------------------
## [Title link text](https://matrix.org)
Attachment text
And more
`<END MX EXAMPLE>`

Slack's formatting appears cleaner:

`<START SLACK EXAMPLE>`
Random message text [matrix.org](https://matrix.org)
> **[Title link text](https://matrix.org)**
> Attachment text
> And more

`<END SLACK EXAMPLE>`

**Comment by Sorunome** [comment]
maybe just bold instead of a heading?

**Comment by twouters** [comment]
Slack formatting can be previewed here: https://api.slack.com/docs/messages/builder

I'm not expecting us to clone the slack formatting, but there's room for improvement :)

**Comment by twouters** [comment]
> maybe just bold instead of a heading?

That might help

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/matrix-slack-parser/commit/1d70518afa3a5c52a47c74268303e44b083bb831
